version: "3.8"

services:

  db:
    image: postgres:14
    container_name: ebankify-postgres
    restart: always
    environment:
      - POSTGRES_DB=eBankify
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    networks:
      - jenkins_network

  sonar-postgres:
    image: postgres:14
    container_name: ebankify-sonar-postgres
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    ports:
      - "5433:5433"
    networks:
      - jenkins_network

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: ebankify-jenkins
    privileged: true
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube:latest
    container_name: ebankify-sonarqube
    restart: always
    depends_on:
      - sonar-postgres
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_data:
