version: "3.8"

services:

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=eBankify
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    networks:
      - jenkins_network

  sonar-postgres:
    image: postgres:14
    container_name: ebankify-sonar-postgres
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    ports:
      - "5433:5433"
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-eBankify
    restart: always
    depends_on:
      - sonar-postgres
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_home: